### ISSUE TITLE
reproduce the results on f30k with a noise rate of 0.8

### ISSUE THREAD

**Issue by cxxPulsar** [QinYang79/CRCL#1]
Hello, thank you for your excellent work! I would like to ask if the parameters in the train.sh file are already configured for the best results on f30k with a noise rate of 0.8? When I run the script with the provided parameters, I only get the following results:

Image to text: 54.0, 79.4, 88.1, 1.0, 9.4
Text to image: 38.4, 65.8, 75.4, 2.0, 21.8
Current rsum is 401.18

However, in the paper, the results are 55.3, 82.1, 89.1, 39.7, 68.2, 77.8, 412.2.
Thanks for your help!

**Comment by QinYang79** [comment]
> Hello, thank you for your excellent work! I would like to ask if the parameters in the train.sh file are already configured for the best results on f30k with a noise rate of 0.8? When I run the script with the provided parameters, I only get the following results:
> 
> Image to text: 54.0, 79.4, 88.1, 1.0, 9.4 Text to image: 38.4, 65.8, 75.4, 2.0, 21.8 Current rsum is 401.18
> 
> However, in the paper, the results are 55.3, 82.1, 89.1, 39.7, 68.2, 77.8, 412.2. Thanks for your help!

Dear friend, I just ran the experiment. Here are my results (slightly better than the paper results) [config.json](https://github.com/user-attachments/files/15603177/config.json) [log.txt](https://github.com/user-attachments/files/15603239/log.txt)


> 2024-06-06 11:32:33,489 => Validation
2024-06-06 11:32:35,643 calculate similarity time:
2024-06-06 11:32:35,804 Image to text: 55.1, 81.3, 89.5, 1.0, 5.7
2024-06-06 11:32:35,930 Text to image: 40.6, 66.3, 76.1, 2.0, 17.9
2024-06-06 11:32:35,930 Current rsum is 408.9
2024-06-06 11:32:35,935 => Test
2024-06-06 11:32:38,122 calculate similarity time:
2024-06-06 11:32:38,283 Image to text: 56.9, 83.1, 91.2, 1.0, 7.6
2024-06-06 11:32:38,407 Text to image: 41.0, 68.7, 78.2, 2.0, 17.8
2024-06-06 11:32:38,407 Current rsum is 419.14

I also uploaded the [noisy index file](https://github.com/QinYang79/CRCL/blob/main/CRCL_NeurIPS23/noisy_index.zip) I used.

**Comment by cxxPulsar** [comment]
Thank you very much for your help! I conducted experiments using your parameter settings and noise files, but the results were still lower by 1-2 points across various noise levels. It’s quite puzzling. I will recheck my setup and look for other possible reasons. Thanks again for your help!

**Comment by QinYang79** [comment]
> Thank you very much for your help! I conducted experiments using your parameter settings and noise files, but the results were still lower by 1-2 points across various noise levels. It’s quite puzzling. I will recheck my setup and look for other possible reasons. Thanks again for your help!

I will also further verify the correctness of my code.

**Comment by QinYang79** [comment]
> Thank you very much for your help! I conducted experiments using your parameter settings and noise files, but the results were still lower by 1-2 points across various noise levels. It’s quite puzzling. I will recheck my setup and look for other possible reasons. Thanks again for your help!

I double-checked and re-ran our code, and the results are still reproduced. 
[Here](https://github.com/user-attachments/files/15651116/environment.zip) are my environment dependencies, I hope that can help you.

**Comment by cxxPulsar** [comment]
Thank you for your patient help!
