### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by ChaitanyaRoygaga** [QinYang79/CRCL#2]
Hi! This is interesting work. 
I was wondering if you could release the model's pretrained weights soon. Thanks!

**Comment by QinYang79** [comment]
> Hi! This is interesting work. I was wondering if you could release the model's pretrained weights soon. Thanks!

Sorry, since the original pre-trained weights were not saved, we are not planning to release them. You can run the version of VSEInfy, it won't take long. Thank you for your interest in our work.
